/*
...
..................................................................................
..............................Logical Operators...................................
..................................................................................
..... Logical AND (&&):                                                      .....
.....               if (condition_1 && condition_2)                          .....
..... True if both condition_1 and condition_2 are true, else false          .....
..................................................................................
..... Logical OR ( || )                                                      .....
.....               if (condition_1 || conditio_2)                           .....
..... True if one or both conditions are true. False if both conditions are  .....
.....                              false                                     .....
..................................................................................
....................................THE END.......................................
..................................................................................
....
*/


#include <stdio.h>

int main()
{
    int a = 50, b = 77;

    // AND (&&) operator
    if (a > 30 && a < 60) printf("true, bczboth conditions are true (AND)\n");
    else printf("false, bcz One or both conditions are true (AND)\n");

    // OR ( || ) operator
    if (a > 30 || b > 100) printf("true, bcz one or both conditions true (OR)\n");
    else printf("false, bcz both conditions are false ( OR )\n");

    return 0;
}